version: "3.8"

services:
  express-ts-webserver:
    build:
      context: ./
    container_name: express-ts-webserver
    environment: 
      NODE_ENV: production
      Server__Port: 80
      Logger__Level: "info"
      Logger__Stream: "bunyan-debug-stream"
      Logger__ShowHeaders: "false"
    ports:
      - "50300:80"
    volumes:
      - "./:/home/node/app"