version: "3.8"

services:
  express-typescript-ws:
    build:
      context: ./
    container_name: express-ws-container
    environment: 
      NODE_ENV: test
      coverage: "true"
      Server__Port: 3005
      Logger__Level: "info"
      Logger__Stream: "bunyan-debug-stream"
      Logger__ShowHeaders: "false"
    ports:
      - "3005:3005"
    volumes:
      - "./:/home/node/app"